project_id = "echrufiutqamgwdcnuap"

[functions.generate-ficha-content]
verify_jwt = false

[functions.generate-inspection-pdf]
verify_jwt = false

[functions.analizar-precio]
verify_jwt = false

[functions.procesar-foto]
verify_jwt = false

[functions.generar-zip-fotos]
verify_jwt = false

[functions.generar-kit-publicacion]
verify_jwt = false
